### ISSUE TITLE
Color Manual Tab

### ISSUE THREAD

**Issue by RenatoGeh** [MarvellousSoft/MarvInc#127] opened 2017-07-05 18:20 UTC
Add color tags to Manual tab, just like emails.

**Comment by yancouto** [comment] 2017-08-04 02:37
I finished this issue. But it looks horrible. I think we should do one or more of the following (all are easy to implement)

- Change the color of the instructions, labels and such (#158)
- Change the background of the manual screen, it's pretty with a black font but not with colorful code.
- Make the text all black again. It wasn't so terrible.

**Comment by rilifon** [comment] 2017-09-29 22:27
I vote we make all thext black and close this issue

**Comment by rilifon** [comment] 2017-09-29 23:26
So I made a new commit creating new colors specefically for the manual based on the originals. Please check them out and give your opinions. If you guys like them, we can close this issue!

**Comment by yancouto** [comment] 2017-10-08 20:28
I still think the colors are WAY too bright and look bad in a green background. I tried multiplying everything by 0.3 to make it darker. It looks better, but I'm not sure if better than black. (Also, address and label blend with the background when near black)

**Comment by rilifon** [comment] 2017-10-08 23:33
Yeah i notices adress and labels are horrible in emails, we need to make them darker. Can you make this changes and commit so we can analyse and maybe close this issue?

**Comment by rilifon** [comment] 2017-10-08 23:34
But I don 't have a problem with keeping all colors black in the manual if you guys want as well.

**Comment by rilifon** [comment] 2017-10-17 07:46
I added border to colored text on the manual tab. Also changed colors for registers and albels on emails since it was unreadable.

I implemented in the most stupid way, but wanted to know your opinions on this refactor. If you guys approve we can close this issue (and maybe open a new issue to refactor the way it is now, since its drawing the same text 5 times to create the border effect)

**Comment by yancouto** [comment] 2017-10-17 09:29
Much better with the border, I think it is a good solution. But it looks weird (glitched) in my computer (probably because of the way it is done), so I don't think we should close this yet.

**Comment by rilifon** [comment] 2017-10-17 21:54
I think for now the issue is solved, but I'm creating a new one so we can refactor it one day to use shaders

**Closed by rilifon** 2017-10-17 21:54 UTC
Labels: enhancement, juice
